CTS_DEFAULT_TARGETS="/home"
CTS_SYSTEM_TARGETS="/home /oldhome /etc /var /opt"

CTS_LOG_DIR="/var/log/clamdscan-tools"
CTS_STATE_DIR="/var/lib/clamdscan-tools/state"
CTS_INFECTED_DIR="/var/lib/clamdscan-tools/infected"

CTS_USE_NICE="yes"
CTS_USE_IONICE="yes"
CTS_CLAMD_SERVICE="clamav-daemon"
CTS_USE_TRACKER="yes"
