/proc
/sys
/dev
/run
/tmp
/var/run
/snap
/var/lib/snapd
/var/lib/docker
$HOME/snap
$HOME/.cache
$HOME/.local/share/Trash
$HOME/.gvfs
$HOME/.steam
$HOME/.var/app
$HOME/VirtualBox VMs
$HOME/.dropbox
$HOME/.dbus
$HOME/.npm
$HOME/.nvm
$HOME/.pnpm-store
$HOME/.cargo
$HOME/.rustup
$HOME/.sdkman
$HOME/.local/share/containers
$HOME/.thumbnails
$HOME/.config/Code/CachedExtensionVSIXs
$HOME/.config/Code/Cache
$HOME/.config/Code/Service Worker/CacheStorage
$HOME/.config/Code/User/workspaceStorage
$CTS_INFECTED_DIR
